name: Check and build the TODOs API (no Nix)

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  check-nonix:
    name: TODOs API checks
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Cache Cargo assets
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: todos-app-${{ hashFiles('**/Cargo.lock') }}

      # Third-party Actions
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          # Required because this Action recognizes rust-toolchain
          # but not rust-toolchain.toml
          toolchain: "1.63.0"
          profile: minimal
          components: clippy, rustfmt
      - name: Check Rust formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --all
      - name: Check Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- --deny warnings
